server:
  port: 9091
  servlet:
    context-path: /
spring:
  application:
    name: car-test
  data:
    rest:
      basePath: /
  datasource:
    initialization-mode: always
    name: ${POSTGRES_DB:car-test}
    password: ${POSTGRES_PASSWORD:postgres}
    platform: postgres
    url: jdbc:postgresql://${DB_URI:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:car-test}
    username: ${POSTGRES_USER:postgres}
  jpa:
    hibernate:
      ddl-auto: ${POSTGRES_INIT_TYPE:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          